project:
  type: book
  output-dir: docs

book:
  title: "R para Ciencias Sociales y Gestión Pública"
  author: "Christian Chiroque Ruiz"
  date: "9/12/2026" #M/D/Y
  chapters:
    - index.qmd
    
    - part: Fundamentos de R
      chapters: 
        - c0_programas.qmd
        - c1_objetos.qmd
        - c2_manipulacion.qmd
        - c3_visualizacion.qmd
        - c4_transformacion.qmd

    # - part: R Intermedio
    #   chapters: 
    #     - 2_c1_dashboards.qmd
    #     - 2_c2_shiny.qmd
    #     - 2_c3_rl.qmd
    #     - 2_c4_rl2.qmd
    #     - 2_c5_cluster1.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

