project:
  type: book
  output-dir: docs

book:
  title: "R_Fundamentos"
  author: "Christian Chiroque Ruiz"
  date: "13/7/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

