project:
  type: book
  output-dir: docs

book:
  title: "Fundamentos de R para Ciencias Sociales y Gestión Pública"
  author: "Christian Chiroque Ruiz"
  date: "7/13/2024"
  chapters:
    - index.qmd
    - c0_programas.qmd
    - c1_objetos.qmd
    - c2_manipulacion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

